### ISSUE TITLE
ProtocolLib WARN

### ISSUE THREAD

**Issue by Sakanas** [ZombieStriker/NPCAuctions#3]
[13:18:31] [Server thread/WARN]: [ProtocolLib] Task #51336 for ProtocolLib v4.4.0-SNAPSHOT-b400 generated an exception
java.lang.NoClassDefFoundError: me/zombie_striker/pluginconstructor/privatemetrics/Metrics$CustomChart
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_171]
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:1.8.0_171]
	at java.lang.Class.privateGetMethodRecursive(Unknown Source) ~[?:1.8.0_171]
	at java.lang.Class.getMethod0(Unknown Source) ~[?:1.8.0_171]
	at java.lang.Class.getMethod(Unknown Source) ~[?:1.8.0_171]
	at com.comphenix.protocol.metrics.Metrics.submitData(Metrics.java:263) ~[?:?]
	at com.comphenix.protocol.metrics.Metrics.access$100(Metrics.java:38) ~[?:?]
	at com.comphenix.protocol.metrics.Metrics$1$1.run(Metrics.java:165) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[PaperSpigot.jar:git-Paper-1471]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) [PaperSpigot.jar:git-Paper-1471]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [PaperSpigot.jar:git-Paper-1471]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [PaperSpigot.jar:git-Paper-1471]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [PaperSpigot.jar:git-Paper-1471]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [PaperSpigot.jar:git-Paper-1471]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.ClassNotFoundException: me.zombie_striker.pluginconstructor.privatemetrics.Metrics$CustomChart
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[PaperSpigot.jar:git-Paper-1471]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[PaperSpigot.jar:git-Paper-1471]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	... 15 more

**Comment by ZombieStriker** [comment]
Odd. I'm surprised that ProtocolLib is the one throwing the error, and that it is because ProtocolLib cant' find my metrics. I'll look into trying to figure it out, but just in case this is a version issue, try downloading the newest version of PluginConstructorAPI and see if the problem persists. If it does, can you post how I could replicate the problem?
https://github.com/ZombieStriker/PluginConstructorAPI/releases/tag/v1.0.40

**Comment by Sakanas** [comment]
Continues

`[19:07:47] [Server thread/WARN]: [ProtocolLib] Task #60697 for ProtocolLib v4.4.0-SNAPSHOT-b403 generated an exception
java.lang.NoClassDefFoundError: me/zombie_striker/pluginconstructor/privatemetrics/Metrics$CustomChart
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_171]
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:1.8.0_171]
	at java.lang.Class.privateGetMethodRecursive(Unknown Source) ~[?:1.8.0_171]
	at java.lang.Class.getMethod0(Unknown Source) ~[?:1.8.0_171]
	at java.lang.Class.getMethod(Unknown Source) ~[?:1.8.0_171]
	at com.comphenix.protocol.metrics.Metrics.submitData(Metrics.java:263) ~[?:?]
	at com.comphenix.protocol.metrics.Metrics.access$100(Metrics.java:38) ~[?:?]
	at com.comphenix.protocol.metrics.Metrics$1$1.run(Metrics.java:165) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[PaperSpigot.jar:git-Paper-1471]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) [PaperSpigot.jar:git-Paper-1471]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [PaperSpigot.jar:git-Paper-1471]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [PaperSpigot.jar:git-Paper-1471]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [PaperSpigot.jar:git-Paper-1471]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [PaperSpigot.jar:git-Paper-1471]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.ClassNotFoundException: me.zombie_striker.pluginconstructor.privatemetrics.Metrics$CustomChart
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[PaperSpigot.jar:git-Paper-1471]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[PaperSpigot.jar:git-Paper-1471]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	... 15 more`
ProtocolLib v4.4.0-SNAPSHOT-b403
NPCAuctions 1.0.37
PluginConstructorAPI : v1.0.40

**Comment by PaqerekYT** [comment]
How to fix it ?
