### ISSUE TITLE
Null Pointer Error Main.onClick

### ISSUE THREAD

**Issue by DahunDev** [ZombieStriker/NPCAuctions#7]
[15:38:42] [Server thread/WARN]: java.lang.NullPointerException
[15:38:42] [Server thread/WARN]: 	at me.zombie_striker.npcauctions.Main.onClick(Main.java:907)
[15:38:42] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor374.invoke(Unknown Source)
[15:38:42] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:38:42] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[15:38:42] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[15:38:42] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[15:38:42] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[15:38:42] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[15:38:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889)
[15:38:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
[15:38:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
[15:38:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[15:38:42] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[15:38:42] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[15:38:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[15:38:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[15:38:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[15:38:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[15:38:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[15:38:42] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[15:38:42] [Server thread/WARN]: java.lang.NullPointerException
[15:38:42] [Server thread/WARN]: 	at me.zombie_striker.npcauctions.Main.onClick(Main.java:907)
[15:38:42] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor374.invoke(Unknown Source)
[15:38:42] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:38:42] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[15:38:42] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[15:38:42] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[15:38:42] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[15:38:42] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[15:38:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889)
[15:38:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
[15:38:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
[15:38:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[15:38:42] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[15:38:42] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[15:38:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[15:38:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[15:38:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[15:38:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[15:38:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[15:38:42] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[15:38:42] [Server thread/WARN]: java.lang.NullPointerException
[15:38:42] [Server thread/WARN]: 	at me.zombie_striker.npcauctions.Main.onClick(Main.java:907)
[15:38:42] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor374.invoke(Unknown Source)
[15:38:42] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:38:42] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[15:38:42] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[15:38:42] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[15:38:42] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[15:38:42] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[15:38:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889)
[15:38:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
[15:38:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
[15:38:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[15:38:42] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[15:38:42] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[15:38:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[15:38:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[15:38:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[15:38:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[15:38:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[15:38:42] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[15:38:43] [Server thread/WARN]: java.lang.NullPointerException
[15:38:43] [Server thread/WARN]: 	at me.zombie_striker.npcauctions.Main.onClick(Main.java:907)
[15:38:43] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor374.invoke(Unknown Source)
[15:38:43] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:38:43] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[15:38:43] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[15:38:43] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[15:38:43] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[15:38:43] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[15:38:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889)
[15:38:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
[15:38:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
[15:38:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[15:38:43] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[15:38:43] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[15:38:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[15:38:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[15:38:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[15:38:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[15:38:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[15:38:43] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[15:38:43] [Server thread/WARN]: java.lang.NullPointerException
[15:38:43] [Server thread/WARN]: 	at me.zombie_striker.npcauctions.Main.onClick(Main.java:907)
[15:38:43] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor374.invoke(Unknown Source)
[15:38:43] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:38:43] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[15:38:43] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[15:38:43] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[15:38:43] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[15:38:43] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[15:38:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889)
[15:38:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
[15:38:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
[15:38:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[15:38:43] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[15:38:43] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[15:38:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[15:38:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[15:38:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[15:38:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[15:38:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[15:38:43] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[15:38:43] [Server thread/WARN]: java.lang.NullPointerException
[15:38:43] [Server thread/WARN]: 	at me.zombie_striker.npcauctions.Main.onClick(Main.java:907)
[15:38:43] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor374.invoke(Unknown Source)
[15:38:43] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[15:38:43] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[15:38:43] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[15:38:43] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[15:38:43] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[15:38:43] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[15:38:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889)
[15:38:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
[15:38:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
[15:38:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[15:38:43] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[15:38:43] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[15:38:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[15:38:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[15:38:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[15:38:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[15:38:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)

**Comment by ZombieStriker** [comment]
This issue should now be fixed as of v1.0.57
