### ISSUE TITLE
Still have NPE And Canceling and List of end Auctions is empty and not working

### ISSUE THREAD

**Issue by DahunDev** [ZombieStriker/NPCAuctions#8]
Still have  java.lang.NullPointerException 

1. And Canceling and List of end Auction is empty even, the auction list exist more than one.

2. java.lang.NullPointerException
        at me.zombie_striker.npcauctions.Main.onClick(Main.java:1025)
        at sun.reflect.GeneratedMethodAccessor953.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889)
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
        at java.lang.Thread.run(Unknown Source)
 java.lang.NullPointerException
        at me.zombie_striker.npcauctions.Main.onClick(Main.java:1025)
        at sun.reflect.GeneratedMethodAccessor953.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889)
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
        at java.lang.Thread.run(Unknown Source)
 java.lang.NullPointerException
        at me.zombie_striker.npcauctions.Main.onClick(Main.java:1025)
        at sun.reflect.GeneratedMethodAccessor953.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889)
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
        at java.lang.Thread.run(Unknown Source)
 java.lang.NullPointerException
        at me.zombie_striker.npcauctions.Main.onClick(Main.java:1025)
        at sun.reflect.GeneratedMethodAccessor953.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889)
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
        at java.lang.Thread.run(Unknown Source)
 java.lang.NullPointerException
        at me.zombie_striker.npcauctions.Main.onClick(Main.java:1025)
        at sun.reflect.GeneratedMethodAccessor953.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889)
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
        at java.lang.Thread.run(Unknown Source)
 java.lang.NullPointerException
        at me.zombie_striker.npcauctions.Main.onClick(Main.java:1025)
        at sun.reflect.GeneratedMethodAccessor953.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889)
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)

        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
        at java.lang.Thread.run(Unknown Source)

**Comment by ZombieStriker** [comment]
Okay, for the error, that is being caused because the item you clicked on was somehow an "air" item, something that should not exist. I've added more checks for that, so that part should work.

However, I don't know about the other auctions. As long as your UUID is the same as the one that created the auction (which is a problem for cracked accounts, in case you have that), it should be able to detect all auctions you created. Can you add a new auction? If so, does that appear when you go to cancel it? If not, are there any other errors in the console?

**Comment by DahunDev** [comment]
Please Add the the CMD or fuction Canceling other's auctions by Administrator.

**Comment by ZombieStriker** [comment]
Sure. V1.0.58 now has the command "/npca cancelAuction <player>" to cancel all of a user's auctions.
