### ISSUE TITLE
java.lang.NumberFormatException

### ISSUE THREAD

**Issue by DahunDev** [ZombieStriker/NPCAuctions#9]
[10:48:43] [Async Chat Thread - #11/WARN]: java.lang.NumberFormatException: For input string: "0:"
[10:48:43] [Async Chat Thread - #11/WARN]: 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[10:48:43] [Async Chat Thread - #11/WARN]: 	at java.lang.Integer.parseInt(Unknown Source)
[10:48:43] [Async Chat Thread - #11/WARN]: 	at java.lang.Integer.parseInt(Unknown Source)
[10:48:43] [Async Chat Thread - #11/WARN]: 	at me.zombie_striker.npcauctions.Main.price(Main.java:680)
[10:48:43] [Async Chat Thread - #11/WARN]: 	at sun.reflect.GeneratedMethodAccessor505.invoke(Unknown Source)
[10:48:43] [Async Chat Thread - #11/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[10:48:43] [Async Chat Thread - #11/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[10:48:43] [Async Chat Thread - #11/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[10:48:43] [Async Chat Thread - #11/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[10:48:43] [Async Chat Thread - #11/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[10:48:43] [Async Chat Thread - #11/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482)
[10:48:43] [Async Chat Thread - #11/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1319)
[10:48:43] [Async Chat Thread - #11/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1257)
[10:48:43] [Async Chat Thread - #11/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39)
[10:48:43] [Async Chat Thread - #11/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[10:48:43] [Async Chat Thread - #11/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[10:48:43] [Async Chat Thread - #11/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[10:48:43] [Async Chat Thread - #11/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[10:48:43] [Async Chat Thread - #11/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by ZombieStriker** [comment]
Colons are not accepted as an input. You will need to use the format <Hours>H [Space] <Minutes>M [Space] <Seconds>S . If you need exact time (exactly 1 minute, exactly 1 hour, ect), you do not need to include the other modifiers (so it would just be "1M" or "1H" respectively)
